package je;
import b.a;

import com.google.ads.mediation.facebook.FacebookMediationAdapter;
import java.util.HashMap;

/* loaded from: classes.dex */
public final class c extends ie.b {

    /* renamed from: d, reason: collision with root package name */
    public static final c f19174d;
    public static final HashMap e = new HashMap();

    /* renamed from: f, reason: collision with root package name */
    public static final HashMap f19175f = new HashMap();

    /* renamed from: g, reason: collision with root package name */
    public static final HashMap f19176g = new HashMap();

    /* renamed from: h, reason: collision with root package name */
    public static final HashMap f19177h = new HashMap();

    static {
        new c("zxx-Zsym-x-autodraw", 0);
        new c("zxx-Zsye-x-emoji", 0);
        new c("zxx-Zsym-x-shapes", 0);
        new c("aa-Latn");
        new c("aa-Latn-x-gesture", 0);
        new c("abs-Latn-ID");
        new c("abs-Latn-ID-x-gesture", 0);
        new c("ace-Latn-ID");
        new c("ace-Latn-ID-x-gesture", 0);
        new c("act-Latn-NL");
        new c("act-Latn-NL-x-gesture", 0);
        new c("af");
        new c("af-x-gesture", 0);
        new c("am");
        new c("am-x-gesture", 0);
        new c("anw-Latn-NG");
        new c("anw-Latn-NG-x-gesture", 0);
        new c("an-Latn-ES");
        new c("an-Latn-ES-x-gesture", 0);
        new c("ar");
        new c("ar-x-gesture", 0);
        new c("as");
        new c("as-x-gesture", 0);
        new c("awa-Deva-IN");
        new c("awa-Deva-IN-x-gesture", 0);
        new c("az-Latn-AZ");
        new c("az-Latn-AZ-x-gesture", 0);
        new c("bah-Latn-BS");
        new c("bah-Latn-BS-x-gesture", 0);
        new c("bar-Latn-AT");
        new c("bar-Latn-AT-x-gesture", 0);
        new c("bcq-Latn-ET");
        new c("bcq-Latn-ET-x-gesture", 0);
        new c("be");
        new c("ber-Latn");
        new c("ber-Latn-x-gesture", 0);
        new c("bew-Latn-ID");
        new c("bew-Latn-ID-x-gesture", 0);
        new c("be-x-gesture", 0);
        new c("bfy-Deva-IN");
        new c("bfy-Deva-IN-x-gesture", 0);
        new c("bfz-Deva-IN");
        new c("bfz-Deva-IN-x-gesture", 0);
        new c("bg");
        new c("bgc-Deva-IN");
        new c("bgc-Deva-IN-x-gesture", 0);
        new c("bgq-Deva-IN");
        new c("bgq-Deva-IN-x-gesture", 0);
        new c("bgq-Deva-PK");
        new c("bgq-Deva-PK-x-gesture", 0);
        new c("bgx-Latn-TR");
        new c("bgx-Latn-TR-x-gesture", 0);
        new c("bgz-Latn-ID");
        new c("bgz-Latn-ID-x-gesture", 0);
        new c("bg-x-gesture", 0);
        new c("bhb-Deva");
        new c("bhb-Deva-x-gesture", 0);
        new c("bho-Deva-IN");
        new c("bho-Deva-IN-x-gesture", 0);
        new c("bik-Latn-PH");
        new c("bik-Latn-PH-x-gesture", 0);
        new c("bi-Latn-VU");
        new c("bi-Latn-VU-x-gesture", 0);
        new c("bjj-Deva-IN");
        new c("bjj-Deva-IN-x-gesture", 0);
        new c("bjn-Latn-ID");
        new c("bjn-Latn-ID-x-gesture", 0);
        new c("bn");
        new c("bn-x-gesture", 0);
        new c("bn-Latn");
        new c("bn-Latn-x-gesture", 0);
        new c("bom-Latn-NG");
        new c("bom-Latn-NG-x-gesture", 0);
        new c("bo-Tibt");
        new c("bo-Tibt-x-gesture", 0);
        new c("brx-Deva");
        new c("brx-Deva-x-gesture", 0);
        new c("brx-Latn");
        new c("brx-Latn-x-gesture", 0);
        new c("bs");
        new c("bs-x-gesture", 0);
        new c("bto-Latn-PH");
        new c("bto-Latn-PH-x-gesture", 0);
        new c("btz-Latn-ID");
        new c("btz-Latn-ID-x-gesture", 0);
        new c("bzc-Latn-MG");
        new c("bzc-Latn-MG-x-gesture", 0);
        new c("ca");
        new c("ca-x-gesture", 0);
        new c("ceb-Latn");
        new c("ceb-Latn-x-gesture", 0);
        new c("cgg-Latn-UG");
        new c("cgg-Latn-UG-x-gesture", 0);
        new c("ch-GU");
        new c("ch-GU-x-gesture", 0);
        new c("cjk-Latn-CD");
        new c("cjk-Latn-CD-x-gesture", 0);
        new c("co-Latn");
        new c("co-Latn-x-gesture", 0);
        new c("cps-Latn-PH");
        new c("cps-Latn-PH-x-gesture", 0);
        new c("crs-Latn-SC");
        new c("crs-Latn-SC-x-gesture", 0);
        new c("cs");
        new c("cs-x-gesture", 0);
        new c("cy");
        new c("cyo-Latn-PH");
        new c("cyo-Latn-PH-x-gesture", 0);
        new c("cy-x-gesture", 0);
        new c("da");
        new c("da-x-gesture", 0);
        new c("de");
        new c("de-AT");
        new c("de-AT-x-gesture", 0);
        new c("de-BE");
        new c("de-BE-x-gesture", 0);
        new c("de-CH");
        new c("de-CH-x-gesture", 0);
        new c("de-DE");
        new c("de-DE-x-gesture", 0);
        new c("de-x-gesture", 0);
        new c("de-LU");
        new c("de-LU-x-gesture", 0);
        new c("dnj-Latn-CI");
        new c("dnj-Latn-CI-x-gesture", 0);
        new c("doi-Deva");
        new c("doi-Deva-x-gesture", 0);
        new c("doi-Latn");
        new c("doi-Latn-x-gesture", 0);
        new c("drs-Latn-ET");
        new c("drs-Latn-ET-x-gesture", 0);
        new c("drt-Latn-NL");
        new c("drt-Latn-NL-x-gesture", 0);
        new c("dsb-DE");
        new c("dsb-DE-x-gesture", 0);
        new c("el");
        new c("el-x-gesture", 0);
        new c("en");
        new c("en-AU");
        new c("en-AU-x-gesture", 0);
        new c("en-CA");
        new c("en-CA-x-gesture", 0);
        new c("en-GB");
        new c("en-GB-x-gesture", 0);
        new c("en-x-gesture", 0);
        new c("en-IN");
        new c("en-IN-x-gesture", 0);
        new c("en-KE");
        new c("en-KE-x-gesture", 0);
        new c("en-NG");
        new c("en-NG-x-gesture", 0);
        new c("en-PH");
        new c("en-PH-x-gesture", 0);
        f19174d = new c("en-US");
        new c("en-US-x-gesture", 0);
        new c("en-ZA");
        new c("en-ZA-x-gesture", 0);
        new c("eo");
        new c("eo-x-gesture", 0);
        new c("es");
        new c("es-AR");
        new c("es-AR-x-gesture", 0);
        new c("es-ES");
        new c("es-ES-x-gesture", 0);
        new c("es-x-gesture", 0);
        new c("es-MX");
        new c("es-MX-x-gesture", 0);
        new c("es-US");
        new c("es-US-x-gesture", 0);
        new c("et");
        new c("et-EE");
        new c("et-EE-x-gesture", 0);
        new c("et-x-gesture", 0);
        new c("eu");
        new c("eu-ES");
        new c("eu-ES-x-gesture", 0);
        new c("eu-x-gesture", 0);
        new c("ext-Latn-ES");
        new c("ext-Latn-ES-x-gesture", 0);
        new c("fa");
        new c("fan-Latn-GQ");
        new c("fan-Latn-GQ-x-gesture", 0);
        new c("fa-x-gesture", 0);
        new c("fi");
        new c("fil-Latn");
        new c("fil-Latn-x-gesture", 0);
        new c("fi-x-gesture", 0);
        new c("fj-FJ");
        new c("fj-FJ-x-gesture", 0);
        new c("fo-FO");
        new c("fo-FO-x-gesture", 0);
        new c("fr");
        new c("fr-002");
        new c("fr-002-x-gesture", 0);
        new c("fr-BE");
        new c("fr-BE-x-gesture", 0);
        new c("fr-CA");
        new c("fr-CA-x-gesture", 0);
        new c("fr-CH");
        new c("fr-CH-x-gesture", 0);
        new c("fr-FR");
        new c("fr-FR-x-gesture", 0);
        new c("fr-x-gesture", 0);
        new c("fy");
        new c("fy-x-gesture", 0);
        new c("ga");
        new c("gax-Latn-ET");
        new c("gax-Latn-ET-x-gesture", 0);
        new c("gay-Latn-ID");
        new c("gay-Latn-ID-x-gesture", 0);
        new c("ga-x-gesture", 0);
        new c("gbm-Deva-IN");
        new c("gbm-Deva-IN-x-gesture", 0);
        new c("gcr-Latn-GF");
        new c("gcr-Latn-GF-x-gesture", 0);
        new c("gdx-Deva-IN");
        new c("gdx-Deva-IN-x-gesture", 0);
        new c("gd-Latn");
        new c("gd-Latn-GB");
        new c("gd-Latn-GB-x-gesture", 0);
        new c("gd-Latn-x-gesture", 0);
        new c("gju-Deva");
        new c("gju-Deva-x-gesture", 0);
        new c("gl");
        new c("gl-ES");
        new c("gl-ES-x-gesture", 0);
        new c("gl-x-gesture", 0);
        new c("gos-Latn-NL");
        new c("gos-Latn-NL-x-gesture", 0);
        new c("gpe-Latn-GH");
        new c("gpe-Latn-GH-x-gesture", 0);
        new c("gsw-CH");
        new c("gsw-CH-x-gesture", 0);
        new c("gu");
        new c("gu-x-gesture", 0);
        new c("gu-Latn");
        new c("gu-Latn-x-gesture", 0);
        new c("gv");
        new c("gv-x-gesture", 0);
        new c("gyn-Latn");
        new c("gyn-Latn-x-gesture", 0);
        new c("haq-Latn-TZ");
        new c("haq-Latn-TZ-x-gesture", 0);
        new c("haw-Latn");
        new c("haw-Latn-x-gesture", 0);
        new c("hdy-Latn");
        new c("hdy-Latn-x-gesture", 0);
        new c("he");
        new c("he-x-gesture", 0);
        new c("hi");
        new c("hif-Deva");
        new c("hif-Deva-x-gesture", 0);
        new c("hil-Latn-PH");
        new c("hil-Latn-PH-x-gesture", 0);
        new c("hi-x-gesture", 0);
        new c("hi-Latn");
        new c("hi-Latn-x-gesture", 0);
        new c("hmn-Latn");
        new c("hmn-Latn-x-gesture", 0);
        new c("hne-Deva-IN");
        new c("hne-Deva-IN-x-gesture", 0);
        new c("hni-Latn-CN");
        new c("hni-Latn-CN-x-gesture", 0);
        new c("hoj-Deva-IN");
        new c("hoj-Deva-IN-x-gesture", 0);
        new c("ho-Latn-PG");
        new c("ho-Latn-PG-x-gesture", 0);
        new c("hr");
        new c("hrx-Latn-BR");
        new c("hrx-Latn-BR-x-gesture", 0);
        new c("hr-x-gesture", 0);
        new c("ht");
        new c("ht-x-gesture", 0);
        new c("hu");
        new c("hu-x-gesture", 0);
        new c("hy");
        new c("hy-x-gesture", 0);
        new c(FacebookMediationAdapter.KEY_ID);
        new c("id-x-gesture", 0);
        new c("igb-Latn-NG");
        new c("igb-Latn-NG-x-gesture", 0);
        new c("ii-Latn");
        new c("ii-Latn-x-gesture", 0);
        new c("ilo-Latn-PH");
        new c("ilo-Latn-PH-x-gesture", 0);
        new c("is");
        new c("is-x-gesture", 0);
        new c("it");
        new c("it-CH");
        new c("it-CH-x-gesture", 0);
        new c("it-x-gesture", 0);
        new c("it-IT");
        new c("it-IT-x-gesture", 0);
        new c("ium-Latn-CN");
        new c("ium-Latn-CN-x-gesture", 0);
        new c("ja");
        new c("jam-Latn-JM");
        new c("jam-Latn-JM-x-gesture", 0);
        new c("jax-Latn-ID");
        new c("jax-Latn-ID-x-gesture", 0);
        new c("ja-x-gesture", 0);
        new c("jbo-Latn");
        new c("jbo-Latn-x-gesture", 0);
        new c("jv-Latn");
        new c("jv-Latn-x-gesture", 0);
        new c("ka");
        new c("ka-x-gesture", 0);
        new c("kde-Latn-TZ");
        new c("kde-Latn-TZ-x-gesture", 0);
        new c("kfr-Deva-IN");
        new c("kfr-Deva-IN-x-gesture", 0);
        new c("kfy-Deva-IN");
        new c("kfy-Deva-IN-x-gesture", 0);
        new c("kge-Latn-ID");
        new c("kge-Latn-ID-x-gesture", 0);
        new c("kha-Latn-IN");
        new c("kha-Latn-IN-x-gesture", 0);
        new c("kj-Latn");
        new c("kj-Latn-x-gesture", 0);
        new c("kk");
        new c("kk-x-gesture", 0);
        new c("kl");
        new c("kl-x-gesture", 0);
        new c("km");
        new c("kmb-Latn-AO");
        new c("kmb-Latn-AO-x-gesture", 0);
        new c("kmz-Latn");
        new c("kmz-Latn-x-gesture", 0);
        new c("km-x-gesture", 0);
        new c("kn");
        new c("kn-x-gesture", 0);
        new c("kn-Latn");
        new c("kn-Latn-x-gesture", 0);
        new c("ko");
        new c("kok");
        new c("kok-x-gesture", 0);
        new c("kok-IN");
        new c("kok-IN-x-gesture", 0);
        new c("kok-Latn");
        new c("kok-Latn-x-gesture", 0);
        new c("ko-x-gesture", 0);
        new c("kru-Deva-IN");
        new c("kru-Deva-IN-x-gesture", 0);
        new c("ksh-Latn-DE");
        new c("ksh-Latn-DE-x-gesture", 0);
        new c("ks-Deva");
        new c("ks-Deva-x-gesture", 0);
        new c("ks-Latn");
        new c("ks-Latn-x-gesture", 0);
        new c("ktb-Latn");
        new c("ktb-Latn-x-gesture", 0);
        new c("ktu-Latn-CD");
        new c("ktu-Latn-CD-x-gesture", 0);
        new c("ku-Latn");
        new c("ku-Latn-x-gesture", 0);
        new c("kw-Latn-GB");
        new c("kw-Latn-GB-x-gesture", 0);
        new c("ky-Cyrl");
        new c("ky-Cyrl-x-gesture", 0);
        new c("la");
        new c("lad-Latn-BA");
        new c("lad-Latn-BA-x-gesture", 0);
        new c("laj-Latn-UG");
        new c("laj-Latn-UG-x-gesture", 0);
        new c("la-x-gesture", 0);
        new c("lb");
        new c("lb-x-gesture", 0);
        new c("led-Latn-CD");
        new c("led-Latn-CD-x-gesture", 0);
        new c("lld-Latn-IT");
        new c("lld-Latn-IT-x-gesture", 0);
        new c("lmn-Deva");
        new c("lmn-Deva-x-gesture", 0);
        new c("lo");
        new c("lon-Latn-MW");
        new c("lon-Latn-MW-x-gesture", 0);
        new c("lo-x-gesture", 0);
        new c("lt");
        new c("lt-x-gesture", 0);
        new c("luy-Latn-KE");
        new c("luy-Latn-KE-x-gesture", 0);
        new c("lv");
        new c("lv-x-gesture", 0);
        new c("mad-Latn-ID");
        new c("mad-Latn-ID-x-gesture", 0);
        new c("mag-Deva-IN");
        new c("mag-Deva-IN-x-gesture", 0);
        new c("mai-IN");
        new c("mai-IN-x-gesture", 0);
        new c("mai-Latn");
        new c("mai-Latn-x-gesture", 0);
        new c("mas-Latn-KE");
        new c("mas-Latn-KE-x-gesture", 0);
        new c("max-Latn-ID");
        new c("max-Latn-ID-x-gesture", 0);
        new c("mdh-Latn-PH");
        new c("mdh-Latn-PH-x-gesture", 0);
        new c("mel-Latn-MY");
        new c("mel-Latn-MY-x-gesture", 0);
        new c("meo-Latn-MY");
        new c("meo-Latn-MY-x-gesture", 0);
        new c("mfb-Latn-ID");
        new c("mfb-Latn-ID-x-gesture", 0);
        new c("mfp-Latn-ID");
        new c("mfp-Latn-ID-x-gesture", 0);
        new c("mg");
        new c("mg-x-gesture", 0);
        new c("min-Latn-ID");
        new c("min-Latn-ID-x-gesture", 0);
        new c("mi-Latn");
        new c("mi-Latn-x-gesture", 0);
        new c("mk");
        new c("mk-x-gesture", 0);
        new c("ml");
        new c("ml-x-gesture", 0);
        new c("ml-Latn");
        new c("ml-Latn-x-gesture", 0);
        new c("mni-Latn");
        new c("mni-Latn-x-gesture", 0);
        new c("mn-Cyrl");
        new c("mn-Cyrl-x-gesture", 0);
        new c("mqy-Latn-ID");
        new c("mqy-Latn-ID-x-gesture", 0);
        new c("mr");
        new c("mrw-Latn-PH");
        new c("mrw-Latn-PH-x-gesture", 0);
        new c("mr-x-gesture", 0);
        new c("mr-IN");
        new c("mr-IN-x-gesture", 0);
        new c("mr-Latn");
        new c("mr-Latn-x-gesture", 0);
        new c("ms");
        new c("msi-Latn-MY");
        new c("msi-Latn-MY-x-gesture", 0);
        new c("ms-BN");
        new c("ms-BN-x-gesture", 0);
        new c("ms-x-gesture", 0);
        new c("ms-MY");
        new c("ms-MY-x-gesture", 0);
        new c("mt");
        new c("mtr-Deva-IN");
        new c("mtr-Deva-IN-x-gesture", 0);
        new c("mt-x-gesture", 0);
        new c("mui-Latn-ID");
        new c("mui-Latn-ID-x-gesture", 0);
        new c("mup-Deva-IN");
        new c("mup-Deva-IN-x-gesture", 0);
        new c("mve-Deva-PK");
        new c("mve-Deva-PK-x-gesture", 0);
        new c("mwr-Deva-IN");
        new c("mwr-Deva-IN-x-gesture", 0);
        new c("mww-Latn-CN");
        new c("mww-Latn-CN-x-gesture", 0);
        new c("my");
        new c("myx-Latn-UG");
        new c("myx-Latn-UG-x-gesture", 0);
        new c("my-x-gesture", 0);
        new c("nah-Latn");
        new c("nah-Latn-x-gesture", 0);
        new c("nap-Latn-IT");
        new c("nap-Latn-IT-x-gesture", 0);
        new c("ndc-Latn-ZW");
        new c("ndc-Latn-ZW-x-gesture", 0);
        new c("ne");
        new c("new-Deva-NP");
        new c("new-Deva-NP-x-gesture", 0);
        new c("ne-x-gesture", 0);
        new c("ne-IN");
        new c("ne-IN-x-gesture", 0);
        new c("ne-Latn");
        new c("ne-Latn-x-gesture", 0);
        new c("ne-NP");
        new c("ne-NP-x-gesture", 0);
        new c("nga-Latn-CD");
        new c("nga-Latn-CD-x-gesture", 0);
        new c("ng-Latn-NA");
        new c("ng-Latn-NA-x-gesture", 0);
        new c("niq-Latn-KE");
        new c("niq-Latn-KE-x-gesture", 0);
        new c("nl-BE");
        new c("nl-BE-x-gesture", 0);
        new c("nl-NL");
        new c("nl-NL-x-gesture", 0);
        new c("nn-NO");
        new c("nn-NO-x-gesture", 0);
        new c("no");
        new c("noe-Deva-IN");
        new c("noe-Deva-IN-x-gesture", 0);
        new c("no-x-gesture", 0);
        new c("nr-ZA");
        new c("nr-ZA-x-gesture", 0);
        new c("nso");
        new c("nso-x-gesture", 0);
        new c("ny");
        new c("nym-Latn-TZ");
        new c("nym-Latn-TZ-x-gesture", 0);
        new c("nyo-Latn-UG");
        new c("nyo-Latn-UG-x-gesture", 0);
        new c("ny-x-gesture", 0);
        new c("oc-Latn-FR");
        new c("oc-Latn-FR-x-gesture", 0);
        new c("oj-Latn");
        new c("oj-Latn-x-gesture", 0);
        new c("olo-Latn-RU");
        new c("olo-Latn-RU-x-gesture", 0);
        new c("om");
        new c("om-x-gesture", 0);
        new c("or");
        new c("or-x-gesture", 0);
        new c("or-Latn");
        new c("or-Latn-x-gesture", 0);
        new c("pa");
        new c("pag-Latn-PH");
        new c("pag-Latn-PH-x-gesture", 0);
        new c("pam-Latn-PH");
        new c("pam-Latn-PH-x-gesture", 0);
        new c("pap-Latn");
        new c("pap-Latn-x-gesture", 0);
        new c("pa-x-gesture", 0);
        new c("pa-Latn");
        new c("pa-Latn-x-gesture", 0);
        new c("pcc-Latn-CN");
        new c("pcc-Latn-CN-x-gesture", 0);
        new c("pcd-Latn-BE");
        new c("pcd-Latn-BE-x-gesture", 0);
        new c("pcm-Latn-NG");
        new c("pcm-Latn-NG-x-gesture", 0);
        new c("pko-Latn-KE");
        new c("pko-Latn-KE-x-gesture", 0);
        new c("pl");
        new c("pl-x-gesture", 0);
        new c("pms-Latn-IT");
        new c("pms-Latn-IT-x-gesture", 0);
        new c("pmy-Latn-ID");
        new c("pmy-Latn-ID-x-gesture", 0);
        new c("pov-Latn-GW");
        new c("pov-Latn-GW-x-gesture", 0);
        new c("prk-Latn-MM");
        new c("prk-Latn-MM-x-gesture", 0);
        new c("pse-Latn-ID");
        new c("pse-Latn-ID-x-gesture", 0);
        new c("pt");
        new c("pt-002");
        new c("pt-002-x-gesture", 0);
        new c("pt-BR");
        new c("pt-BR-x-gesture", 0);
        new c("pt-x-gesture", 0);
        new c("pt-PT");
        new c("pt-PT-x-gesture", 0);
        new c("quc-Latn");
        new c("quc-Latn-x-gesture", 0);
        new c("qu-PE");
        new c("qu-PE-x-gesture", 0);
        new c("rcf-Latn-RE");
        new c("rcf-Latn-RE-x-gesture", 0);
        new c("rkt-Deva-IN");
        new c("rkt-Deva-IN-x-gesture", 0);
        new c("rm-CH");
        new c("rm-CH-x-gesture", 0);
        new c("rn-BI");
        new c("rn-BI-x-gesture", 0);
        new c("ro-RO");
        new c("ro-RO-x-gesture", 0);
        new c("ru");
        new c("ru-x-gesture", 0);
        new c("rwr-Deva-IN");
        new c("rwr-Deva-IN-x-gesture", 0);
        new c("sat-Deva");
        new c("sat-Deva-x-gesture", 0);
        new c("sat-Latn");
        new c("sat-Latn-x-gesture", 0);
        new c("sa-Deva-IN");
        new c("sa-Deva-IN-x-gesture", 0);
        new c("sa-Latn");
        new c("sa-Latn-x-gesture", 0);
        new c("sck-Deva-IN");
        new c("sck-Deva-IN-x-gesture", 0);
        new c("sco-Latn-GB");
        new c("sco-Latn-GB-x-gesture", 0);
        new c("sc-Latn-IT");
        new c("sc-Latn-IT-x-gesture", 0);
        new c("sdc-Latn-IT");
        new c("sdc-Latn-IT-x-gesture", 0);
        new c("sd-Deva");
        new c("sd-Deva-x-gesture", 0);
        new c("sd-Latn");
        new c("sd-Latn-x-gesture", 0);
        new c("sgc-Latn-KE");
        new c("sgc-Latn-KE-x-gesture", 0);
        new c("sgj-Deva-IN");
        new c("sgj-Deva-IN-x-gesture", 0);
        new c("sgs-Latn-LT");
        new c("sgs-Latn-LT-x-gesture", 0);
        new c("sg-CF");
        new c("sg-CF-x-gesture", 0);
        new c("si");
        new c("si-x-gesture", 0);
        new c("sk");
        new c("skg-Latn-MG");
        new c("skg-Latn-MG-x-gesture", 0);
        new c("sk-x-gesture", 0);
        new c("sl");
        new c("sl-x-gesture", 0);
        new c("sm");
        new c("sm-x-gesture", 0);
        new c("sn-Latn");
        new c("sn-Latn-x-gesture", 0);
        new c("so");
        new c("so-x-gesture", 0);
        new c("sq");
        new c("sq-x-gesture", 0);
        new c("sr-Cyrl");
        new c("sr-Cyrl-x-gesture", 0);
        new c("sr-Latn-RS");
        new c("sr-Latn-RS-x-gesture", 0);
        new c("ss-SZ");
        new c("ss-SZ-x-gesture", 0);
        new c("stv-Latn");
        new c("stv-Latn-x-gesture", 0);
        new c("suk-Latn-TZ");
        new c("suk-Latn-TZ-x-gesture", 0);
        new c("su-Latn");
        new c("su-Latn-x-gesture", 0);
        new c("sv-FI");
        new c("sv-FI-x-gesture", 0);
        new c("sv-SE");
        new c("sv-SE-x-gesture", 0);
        new c("sw");
        new c("swv-Deva-IN");
        new c("swv-Deva-IN-x-gesture", 0);
        new c("sw-x-gesture", 0);
        new c("sxu-Latn-DE");
        new c("sxu-Latn-DE-x-gesture", 0);
        new c("syl-Latn");
        new c("syl-Latn-x-gesture", 0);
        new c("ta");
        new c("ta-x-gesture", 0);
        new c("ta-Latn");
        new c("ta-Latn-x-gesture", 0);
        new c("tdx-Latn-MG");
        new c("tdx-Latn-MG-x-gesture", 0);
        new c("te");
        new c("tet-Latn-TL");
        new c("tet-Latn-TL-x-gesture", 0);
        new c("te-x-gesture", 0);
        new c("te-Latn");
        new c("te-Latn-x-gesture", 0);
        new c("tg-Cyrl");
        new c("tg-Cyrl-x-gesture", 0);
        new c("th");
        new c("th-x-gesture", 0);
        new c("ti");
        new c("ti-x-gesture", 0);
        new c("tk-Latn");
        new c("tk-Latn-x-gesture", 0);
        new c("tn-BW");
        new c("tn-BW-x-gesture", 0);
        new c("tpi");
        new c("tpi-x-gesture", 0);
        new c("trf-Latn-TT");
        new c("trf-Latn-TT-x-gesture", 0);
        new c("trp-Latn");
        new c("trp-Latn-x-gesture", 0);
        new c("tr-TR");
        new c("tr-TR-x-gesture", 0);
        new c("ts");
        new c("tsg-Latn-PH");
        new c("tsg-Latn-PH-x-gesture", 0);
        new c("ts-x-gesture", 0);
        new c("tum-Latn-MW");
        new c("tum-Latn-MW-x-gesture", 0);
        new c("tuv-Latn-KE");
        new c("tuv-Latn-KE-x-gesture", 0);
        new c("twd-Latn-NL");
        new c("twd-Latn-NL-x-gesture", 0);
        new c("uk");
        new c("uk-x-gesture", 0);
        new c("unr-Deva-IN");
        new c("unr-Deva-IN-x-gesture", 0);
        new c("unr-Latn");
        new c("unr-Latn-x-gesture", 0);
        new c("ur");
        new c("ur-x-gesture", 0);
        new c("ur-Latn");
        new c("ur-Latn-x-gesture", 0);
        new c("ur-PK");
        new c("ur-PK-x-gesture", 0);
        new c("uz-Latn");
        new c("uz-Latn-x-gesture", 0);
        new c("vel-Latn-NL");
        new c("vel-Latn-NL-x-gesture", 0);
        new c("vep-Latn-RU");
        new c("vep-Latn-RU-x-gesture", 0);
        new c("vi");
        new c("vi-x-gesture", 0);
        new c("vkt-Latn-ID");
        new c("vkt-Latn-ID-x-gesture", 0);
        new c("wa-Latn-BE");
        new c("wa-Latn-BE-x-gesture", 0);
        new c("wbr-Deva-IN");
        new c("wbr-Deva-IN-x-gesture", 0);
        new c("wry-Deva-IN");
        new c("wry-Deva-IN-x-gesture", 0);
        new c("xh");
        new c("xh-x-gesture", 0);
        new c("xmm-Latn-ID");
        new c("xmm-Latn-ID-x-gesture", 0);
        new c("xnr-Deva-IN");
        new c("xnr-Deva-IN-x-gesture", 0);
        new c("ymm-Latn-SO");
        new c("ymm-Latn-SO-x-gesture", 0);
        new c("za-Latn-CN");
        new c("za-Latn-CN-x-gesture", 0);
        new c("zh-Hani");
        new c("zh-Hani-CN");
        new c("zh-Hani-CN-x-gesture", 0);
        new c("zh-Hani-x-gesture", 0);
        new c("zh-Hani-HK");
        new c("zh-Hani-HK-x-gesture", 0);
        new c("zh-Hani-TW");
        new c("zh-Hani-TW-x-gesture", 0);
        new c("zu");
        new c("zu-x-gesture", 0);
        new c("zyj-Latn-CN");
        new c("zyj-Latn-CN-x-gesture", 0);
    }

    public c(String str) {
        super(str, false);
    }

    public static c b(String str) {
        String str2;
        int i;
        int i10;
        ie.a aVar = new ie.a(str);
        String str3 = aVar.f18433a;
        HashMap hashMap = f19175f;
        int i11 = 0;
        ie.b bVar = null;
        for (ie.b bVar2 : ie.a(str3, hashMap)) {
            int a10 = aVar.a(bVar2.f18439b);
            if (a10 > i11) {
                i10 = a10;
            } else {
                i10 = i11;
            }
            if (a10 > i11) {
                bVar = bVar2;
            }
            i11 = i10;
        }
        if (bVar == null && (str2 = aVar.f18436d) != null) {
            for (ie.b bVar3 : ie.a(str2, hashMap)) {
                int a11 = aVar.a(bVar3.f18439b);
                if (a11 > i11) {
                    i = a11;
                } else {
                    i = i11;
                }
                if (a11 > i11) {
                    bVar = bVar3;
                }
                i11 = i;
            }
        }
        return (c) bVar;
    }

    @Override // ie.b
    public final boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof c)) {
            return false;
        }
        return super.equals(obj);
    }

    public c(String str, int i) {
        super(str, true);
    }
}
